server:
  port: 9093

spring:
  application:
    name: user-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
  grpc:
    server:
      port: 9092
