server:
  port: 9091

spring:
  application:
    name: movie-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
      instance:
        metadata-map:
          gRPC.port:${grpc.server.port}
  grpc:
    server:
      port: 9090